### ISSUE TITLE
Blank line produces headers cannot sent error

### ISSUE THREAD

**Issue by dmolineus** [trilobit-gmbh/contao-pixabay-bundle#1]
There is an empty line at the top of the file which produces a headers cannot sent error.

https://github.com/trilobit-gmbh/contao-pixabay-bundle/blob/831484a6675ca4fd9bade0baccb61a2c6fb0c89c/src/Resources/contao/dca/tl_settings.php#L1

**Comment by trilobit-gmbh** [comment]
Fixed in 1.0.4.
Thanks for the message ;-)
