### ISSUE TITLE
Error downloading images when using 'fullHDURL'

### ISSUE THREAD

**Issue by m-vo** [trilobit-gmbh/contao-pixabay-bundle#2]
To reproduce: 
- select `1280 pixels wide` as source in settings
- try downloading an image

----
The problem can be traced to the following piece of code:

`$arrApiData['id'][$value['id']]['files']['download']` from here ...
https://github.com/trilobit-gmbh/contao-pixabay-bundle/blob/d29a0a728c13ab394d39b134d8bfb398f6e9345d/src/Resources/contao/drivers/DC_Folder_pixabay.php#L117-L126

... gets overwritten right away in line 128:
https://github.com/trilobit-gmbh/contao-pixabay-bundle/blob/d29a0a728c13ab394d39b134d8bfb398f6e9345d/src/Resources/contao/drivers/DC_Folder_pixabay.php#L128

The first statement is redundant, the latter one fails in my case because `$strImageSource` equals `fullHDURL` which isn't a key in `$value` thus rendering the whole thing to `NULL`. Obviously this leads to a `file_get_contents()` call on `NULL` and so on...

Commenting out that line allows downloading images (in low resolution though, URLs like *https://pixabay.com/get/eb3[...]cb9_640.jpg*).

**Comment by trilobit-gmbh** [comment]
fixed ;-) 

If the desired key is not available, a general fallback is used. There is an entry in the log. The user is informed about the status.
